<?php
namespace CakephpSurvey\Controller;

use CakephpSurvey\Controller\AppController;

/**
 * Manage Controller
 *
 * @property \CakephpSurvey\Model\Table\ManageTable $Manage
 */
class ManageController extends AppController
{
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        $user = $this->Auth->user();
        if ($user['user_type'] == 'sys'){
            $this->Auth->allow();
            $this->loadModel('Survey');
        }
    }

    /**
     * Index method
     *
     * @return \Cake\Network\Response|null
     */
    public function index()
    {
        $survey = $this->paginate($this->Survey);
        $this->viewBuilder()->layout('default');
        $this->set(compact('survey'));
        $this->set('_serialize', ['survey']);
    }

    /**
     * View method
     *
     * @param string|null $id Manage id.
     * @return \Cake\Network\Response|null
     * @throws \Cake\Datasource\Exception\RecordNotFoundException When record not found.
     */
    public function view($id = null)
    {
        $manage = $this->Manage->get($id, [
            'contain' => []
        ]);
        $this->set('manage', $manage);
        $this->set('_serialize', ['manage']);
    }

    /**
     * Add method
     *
     * @return \Cake\Network\Response|void Redirects on successful add, renders view otherwise.
     */
    public function add()
    {
        $survey = $this->Survey->newEntity();
        $this->loadModel('SurveyQuestions');
        $questions = $this->SurveyQuestions->find('list');
        $this->viewBuilder()->layout('default');
        if ($this->request->is('post')) {
            $input = $this->request->data;

        }
        $this->set(compact('survey','questions'));
        $this->set('_serialize', ['survey','questions']);
    }
}
